- block:
    - name: Ensure group "etcd" exists
      ansible.builtin.group:
        name: etcd
        state: present
    - name: add user etcd
      user:
        name: etcd
        append: yes
        groups: etcd
        state: present
    - name: "Create directory for etcd binaries"
      file:
        path: /opt/etcd/bin
        state: directory
        owner: etcd
        group: etcd
        mode: 0755
    - name: "Download the tarball into the /tmp directory"
      get_url:
        url: https://github.com/etcd-io/etcd/releases/download/v3.5.2/etcd-v3.5.2-linux-amd64.tar.gz
        dest: /tmp/etcd.tar.gz
        owner: etcd
        group: etcd
        mode: 0600
        force: True
    - name: "Extract the contents of the tarball"
      unarchive:
        src: /tmp/etcd.tar.gz
        dest: /opt/etcd/bin/
        owner: etcd
        group: etcd
        mode: 0755
        extra_opts:
          - --strip-components=1
        decrypt: True
        remote_src: True
    - name: "Set permissions for etcd"
      file:
        path: /opt/etcd/bin/etcd
        state: file
        owner: etcd
        group: etcd
        mode: 0755
    - name: "Set permissions for etcdctl"
      file:
        path: /opt/etcd/bin/etcdctl
        state: file
        owner: etcd
        group: etcd
        mode: 0755
    - name: "Add /opt/etcd/bin/ to the $PATH environment variable"
      lineinfile:
        path: /etc/profile
        line: export PATH="$PATH:/opt/etcd/bin"
        state: present
        create: True
        insertafter: EOF
    - name: "Set the ETCDCTL_API environment variable to 3"
      lineinfile:
        path: /etc/profile
        line: export ETCDCTL_API=3
        state: present
        create: True
        insertafter: EOF
    - name: "Create a etcd service"
      ansible.builtin.template:
        src: templates/etcd.service.j2
        dest: /etc/systemd/system/etcd.service
        owner: etcd
        group: etcd
        mode: 0644
    - name: "Create a etcd default"
      ansible.builtin.template:
        src: templates/etcd.j2
        dest: /etc/default/etcd
        owner: etcd
        group: etcd
        mode: 0755
    - name: "Create a data directory"
      file:
        path: /var/lib/etcd/default
        state: directory
        owner: etcd
        group: etcd
        mode: 0755
    - name: Recursively remove directory /var/lib/etcd/member
      ansible.builtin.file:
        path: /var/lib/etcd/member
        state: absent
    - name: etcd enable & start
      systemd:
        name: etcd
        enabled: yes
        state: started
  tags:
    - etcd