- block:
  - name: haproxy install
    dnf:
      name: haproxy
      state: latest
  - name: haproxy config file 1
    ansible.builtin.template:
      src: templates/haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      backup: yes
  - name: haproxy enable & start
    systemd:
      name: haproxy
      enabled: yes
      state: started
  - name: haproxy restart
    systemd:
      name: haproxy
      state: restarted
  tags:
    - haproxy
