- block:
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
  - name: disable firewall
    systemd:
      name: firewalld
      state: stopped
      enabled: no
  - name: Disable SELinux
    ansible.posix.selinux:
      state: disabled
  tags:
    - settings